#version: '3.8'

services:
    # Laravel (PHP-FPM) konteyneri
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: btob_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_DATABASE=db_btob
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
        networks:
            - laravel_network

    # Nginx konteyneri
    nginx:
        image: nginx:alpine
        container_name: btob_nginx
        restart: unless-stopped
        ports:
            - "8001:80"  # 8000 port orqali kirish
        volumes:
            - .:/var/www
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - laravel_network

    # PostgreSQL konteyneri
    postgres:
        image: postgres:13
        container_name: btob_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: db_btob
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5433:5432"  # PostgreSQL uchun 5432 port ochilgan
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - laravel_network

    # pgAdmin konteyneri
    pgadmin:
        image: dpage/pgadmin4
        container_name: btob_pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5051:80"  # pgAdmin uchun 5050 port ochilgan
        networks:
            - laravel_network
networks:
    laravel_network:
        driver: bridge

volumes:
    postgres_data:
